-- V1__Create_enum_types.sql

CREATE TYPE product_type_enum AS ENUM ('FINANCIAL', 'NON_FINANCIAL');
CREATE TYPE product_status_enum AS ENUM ('PROPOSED', 'ACTIVE', 'RETIRED');
CREATE TYPE feature_type_enum AS ENUM ('STANDARD', 'OPTIONAL', 'PREMIUM');
CREATE TYPE pricing_type_enum AS ENUM ('INTEREST_RATE', 'FEE', 'COVERAGE', 'SUBSCRIPTION');
CREATE TYPE doc_type_enum AS ENUM ('TNC', 'BROCHURE', 'POLICY_DOC');
CREATE TYPE lifecycle_status_enum AS ENUM ('PROPOSED', 'ACTIVE', 'SUSPENDED', 'RETIRED');
CREATE TYPE limit_type_enum AS ENUM ('CREDIT_LIMIT', 'WITHDRAWAL_LIMIT', 'SUBSCRIPTION_LIMIT');
CREATE TYPE time_period_enum AS ENUM ('DAILY', 'MONTHLY', 'PER_TRANSACTION', 'NONE');
CREATE TYPE bundle_status_enum AS ENUM ('ACTIVE', 'RETIRED', 'PROMO');
CREATE TYPE relationship_type_enum AS ENUM ('PRE_REQUISITE', 'COMPLIMENTARY', 'UPGRADE', 'CROSS_SELL');
CREATE TYPE fee_structure_type_enum AS ENUM ('VERTICAL', 'HORIZONTAL');
CREATE TYPE fee_type_enum AS ENUM ('ORIGINATION_FEE', 'LATE_PAYMENT_FEE', 'TRANSACTION_FEE', 'SERVICE_FEE');
CREATE TYPE fee_unit_enum AS ENUM ('FIXED', 'PERCENTAGE');